title: Janpreet Singh
email: hire@janpreet.com
author: ਜਨਪ੍ਰੀਤ ਸਿੰਘ
description: >-
  Join me on a journey of self-discovery and learning, as I explore the exciting world of DevOps and home-automation. This space documents my learnings, experiences, and growth as a self-taught enthusiast.
baseurl: "/"
disqus:
  shortname: janpreet
url: "https://janpreet.com"
twitter_username: SinghJanpreet
github_username:  Janpreet
linkedin_username: Janpreet

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  - scope:
      path: "assets/"
    values:
      images: true

show_excerpts: true 

header_pages:
  - index.md
  - about.md
  - contact.md
  - resume.md
  
permalink: pretty  
redirect_from:
  json: false