title: Janpreet Singh
email: hire@janpreet.com
author: ਜਨਪ੍ਰੀਤ ਸਿੰਘ
description: >-
  SRE by day, baker and tinkerer by night. Writing about infrastructure, home networking, personal growth, nostalgia, and sourdough.
baseurl: "/"
url: "https://janpreet.com"
github_username:  Janpreet
linkedin_username: Janpreet

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  - scope:
      path: "assets/"
    values:
      images: true

show_excerpts: true 

header_pages:
  - index.md
  - about.md
  - sikhi.md

permalink: pretty  
redirect_from:
  json: false